import { faker } from "@faker-js/faker";

const generateRandomThought = () => {
  const templates = [
    "I can't believe how amazing it was to see {thing} today!",
    "Feeling {emotion} about {topic}. Can't wait to see what happens next!",
    "Anyone else feel like {randomThought}? Or is it just me?",
    "Honestly, {thing} has been on my mind a lot lately.",
    "Just realized how much I appreciate {thing}. Life’s funny like that!",
    "Can't stop thinking about {thing}. Anyone else?",
    "When life gives you {thing}, make it memorable.",
    "Today felt {emotion}... and it's all because of {thing}.",
    "I've been feeling so {emotion} about {person} lately.",
    "Anyone else obsessed with {thing}? Just me?",
    "Why does {thing} always make me feel {emotion}?",
    "I finally tried {thing} today, and wow!",
    "Feeling all the feels about {thing} right now.",
    "Is there anything better than {thing}? I think not!",
    "One word: {thing}. It’s everything.",
    "You know, {person} has really been inspiring me lately.",
    "{topic} can be so {emotion} sometimes!",
    "So {emotion} right now, thanks to {thing}.",
    "If only I could explain why {thing} means so much!",
    "Today was all about {thing} for me.",
    "Can anyone else relate to feeling {emotion} about {person}?",
    "Every time I think about {thing}, it makes me {emotion}.",
    "Can't wait to experience more of {thing}.",
    "{thing} just made my day so much better!",
    "Isn't it amazing when {thing} surprises you?",
    "I'm so grateful for {thing}.",
    "I wish everyone could experience {thing}.",
    "{thing} was a game-changer today.",
    "I’m always blown away by {thing}.",
    "Some days you just need a little {thing}.",
    "I had the best time with {person} today!",
    "{thing} really hit different today.",
    "Random thought: {thing} is the best!",
    "If you haven’t tried {thing} yet, you’re missing out!",
    "Today’s happiness is brought to you by {thing}.",
    "Nothing beats the feeling of {thing}.",
    "{thing} or nothing. That’s my mood today.",
    "Is there a word for being {emotion} about {thing}?",
    "I swear, {thing} just gets better and better.",
    "If you know, you know: {thing} is everything.",
    "The more I experience {thing}, the more I love it.",
    "Every day feels {emotion} with {thing}.",
    "My heart is so full of {thing} right now.",
    "{thing} is giving me all the feels today.",
    "Why am I so invested in {thing}? It’s unreal.",
    "No words can explain my love for {thing}.",
    "I thought I knew {thing}, but today changed everything.",
    "{thing} has completely stolen my heart.",
    "Sometimes, all you need is a little {thing}.",
    "Feeling {emotion} because {thing} is just perfect.",
    "Does anyone else get nostalgic thinking about {thing}?",
    "Today, {thing} reminded me to appreciate the little things.",
    "Feeling all kinds of {emotion} after today’s {thing}.",
    "The magic of {thing} never gets old!",
    "{thing} has become my new obsession.",
    "{thing} + today = {emotion}.",
    "If {thing} doesn’t make you {emotion}, I don’t know what will.",
    "Nothing but {emotion} vibes thanks to {thing}.",
    "{thing} made me realize how {emotion} life can be.",
    "It’s always a {emotion} day with {thing}.",
    "I never knew {thing} could bring so much {emotion}.",
    "{thing} has been my comfort lately.",
    "Today felt complete because of {thing}.",
    "Thankful for {thing} and all it brings.",
    "Why does {thing} always make me smile?",
    "Thinking about {thing} gives me all the {emotion} vibes.",
    "I’m convinced {thing} is life’s best gift.",
    "There’s nothing like the joy of {thing}.",
    "Is it possible to love {thing} too much?",
    "My love for {thing} grows every day.",
    "Why does {thing} always make everything feel right?",
    "Just spent my day with {thing}. No regrets!",
    "Ever feel {emotion} just thinking about {thing}?",
    "{thing} has become my happy place.",
    "Sometimes, I just need {thing} to feel complete.",
    "Today, {thing} made me feel so {emotion}.",
    "Why am I always so {emotion} about {thing}?",
    "Never a dull moment with {thing} in my life.",
    "{thing} has been the highlight of my week!",
    "{thing} gives me something to look forward to.",
    "Can’t imagine life without {thing}.",
    "It’s been a {emotion} day, all thanks to {thing}.",
    "Couldn’t be more {emotion} about {thing}.",
    "Why does {thing} always make me feel so alive?",
    "How is it possible to be this {emotion} about {thing}?",
    "{thing} brought so much joy to my day!",
    "I didn’t realize how much I needed {thing}.",
    "Sometimes, {thing} is all I need to feel {emotion}.",
    "Anyone else {emotion} just thinking about {thing}?",
    "{thing} feels like a blessing today.",
    "{thing} really put a smile on my face.",
    "{thing} has brought so much {emotion} to my life.",
    "How can something like {thing} be so perfect?",
    "Today was all about {thing} and {emotion} vibes!",
    "I’m starting to realize just how special {thing} is.",
    "{thing} makes me {emotion} in the best way possible.",
    "Honestly, {thing} makes every day feel special.",
    "There’s something about {person} that just makes life better.",
    "Having {thing} in my life is like a breath of fresh air.",
    "{person} has been on my mind nonstop. I can’t explain it!",
    "Just had the best conversation with {person}. They're amazing!",
    "I've been obsessed with {thing} lately... it's unreal.",
    "Feeling super {emotion} today. Thanks, {thing}!",
    "Ever met someone who makes you feel {emotion} just by being around?",
    "I’m so glad I tried {thing}. Life will never be the same.",
    "Random thought: I need more {thing} in my life!",
    "Can’t get over how {emotion} today felt.",
    "If only {person} knew how much they mean to me.",
    "Is there anything better than {person} and {thing} together?",
    "You know those moments when {thing} just hits right?",
    "Not gonna lie, {thing} made my day.",
    "Today was filled with so much {emotion}, and I’m grateful.",
    "If there’s one thing I’m sure of, it’s that {thing} is magic.",
    "Why am I so attached to {thing}? It just feels right.",
    "{thing} + {person} = absolute bliss.",
    "Anyone else feel a wave of {emotion} thinking about {thing}?",
    "{thing} might be the best discovery of my life!",
    "Here’s to more days filled with {thing} and {emotion}.",
    "Feeling grateful for {thing} and everything it brings.",
    "Sometimes, {thing} is all I need to smile."
  ];

  const randomTemplate = templates[Math.floor(Math.random() * templates.length)];

  return randomTemplate
    .replace("{thing}", faker.food.dish())
    .replace("{emotion}", faker.word.adjective())
    .replace("{topic}", faker.lorem.word())
    .replace("{randomThought}", faker.hacker.phrase())
    .replace("{person}", faker.person.firstName());
}

export default generateRandomThought;
